name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x86_64-linux
            os: ubuntu-latest
          - name: aarch64-linux
            os: ubuntu-24.04-arm
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@v3.8.2
        with:
          extra-config: accept-flake-config = true

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Check flake
        run: nix flake check --show-trace --print-build-logs --verbose --accept-flake-config

      - name: Run Cabal tests
        run: nix develop --accept-flake-config -c cabal test all
