name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@v3.8.2
        with:
          extra-config: accept-flake-config = true

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Check flake
        run: nix flake check --show-trace --print-build-logs --verbose --accept-flake-config
